exclude_patterns:
- "**/test/"
- "**/androidTest/"
- "**test"

plugins:
  duplication:
    enabled: true
    config:
      languages:
        kotlin:
          mass_threshold: 20
        java:
          mass_threshold: 20